kind: Deployment
apiVersion: apps/v1
metadata:
  name:  my-react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-jenkins-deployment
  template:
    metadata:
      labels:
        app: test-jenkins-deployment
    spec:
      containers:
        - name: test-jenkins-deployment
          image: localhost:5000/test-jenkins-deployment:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: test-jenkins-deployment
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: test-jenkins-deployment